# Generated by Django 2.2.4 on 2019-10-14 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ürün')),
                ('price', models.FloatField(default=0, verbose_name=40)),
                ('hire_date', models.DateTimeField(auto_now_add=True, verbose_name='Kiralama Tarihii')),
                ('hire_end_date', models.DateTimeField(auto_now_add=True, verbose_name='Kiralık Bitiş Tarihi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Urun Sahibi')),
            ],
        ),
    ]
