# Generated by Django 2.2.4 on 2019-10-24 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191014_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='product'),
        ),
    ]
