# Generated by Django 2.2.4 on 2019-10-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productmodel_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='hire_end_date',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
