# Generated by Django 2.2.4 on 2019-11-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20191101_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='hire_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Şuan'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='hire_end_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiralık Bitiş Tarihi'),
        ),
    ]
