# Generated by Django 2.2.4 on 2019-11-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20191101_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='hire_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Şuan'),
        ),
    ]
