# Generated by Django 2.2.4 on 2019-11-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20191101_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='hire_date',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='hire_start_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kira Başlangıcı'),
        ),
    ]
