# Generated by Django 2.2.4 on 2019-11-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20191101_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.CharField(blank=True, default="'Belirtilmedi", max_length=500, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(default="'Belirtilmedi", max_length=30, verbose_name='Ürün Adı'),
        ),
    ]
