# Generated by Django 2.2.4 on 2019-11-04 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20191102_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.CharField(blank=True, default="'Belirtilmedi'", max_length=500, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='hirer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiraci', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Ürün Adı'),
        ),
    ]
