# Generated by Django 2.2.4 on 2019-12-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20191127_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-create_date']},
        ),
    ]
