# Generated by Django 2.2.4 on 2019-10-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.FloatField(default=0, verbose_name='Para'),
        ),
    ]
