# Generated by Django 2.2.4 on 2019-11-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_nestedcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deneme',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=300, verbose_name='Yorum'),
        ),
    ]
