# Generated by Django 2.2.4 on 2019-11-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20191101_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deneme',
        ),
    ]
