# Generated by Django 2.2.4 on 2019-11-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20191101_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=40, verbose_name='Yorum'),
        ),
    ]
