# Generated by Django 2.2.4 on 2019-11-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20191104_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=300, verbose_name='Yorum'),
        ),
    ]
