# Generated by Django 2.2.4 on 2019-11-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_auto_20191104_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=50, verbose_name='Yorum'),
        ),
    ]
