# Generated by Django 2.2.4 on 2019-11-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_auto_20191127_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=300, verbose_name='Yorum'),
        ),
    ]
